[package]
name = "stopsui"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
# Pyth Oracle for price feeds (Wormhole is included as transitive dep)
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet" }

[addresses]
stopsui = "0x0"

[dev-addresses]
stopsui = "0x0"
