[package]
name = "stopsui"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
# Sui framework is auto-included

[addresses]
stopsui = "0x0"
# Pyth mainnet package - we'll call this via PTB at runtime
pyth = "0x04e20ddf36af412a4096f9014f4a565af9e812db9a05cc40254846cf6ed0ad91"

[dev-addresses]
stopsui = "0x0"
